logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example.demo: DEBUG

server.error.include-message: always
server.shutdown: graceful

postgresql:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: 1234

redis:
  host: localhost
  port: 6379
  