logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example.demo: DEBUG
  # pattern:
    # console: "%a %A %h %H %m %r %s %D %U %S %v %I %n"

server.error.include-message: always

postgresql:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: 1234
